# fly.toml app configuration file generated for imlek-fe-p6k-pg on 2025-01-06T10:52:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "imlek-fe"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
