name: Build Docker image
on:
  push:
    branches:
      - main

jobs: 
  build_and_upload:
    name: Build Docker image and upload artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: meta
        uses: docker/metadata-action@v5
      - uses: docker/build-push-action@v6
        id: dbuild
        with:
            build-args: 
                APP_ENV="production"
            push: false
            tags: imlek/package-validator-fe:${{ github.sha }}
      - run: docker save -o imlek-package-validator-fe-${{ github.sha }}.tar imlek/package-validator-fe:${{ github.sha }}
      - uses: actions/upload-artifact@v4
        with:
          name: latest-docker-image
          path: imlek-package-validator-fe-${{ github.sha }}.tar